# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 058398df7971fcda8134f666fe3e94a7f8976c7bfe10e82d6421c66efce07fa9813567e6a0fdf0ed77aab25934629dfb72dc98975b9be9c2b2038453d39ac8e8

test:
  secret_key_base: 2e67d11a77096cc5bf9cced81c8faf86b5ca3200abb5b19c9ae6da37d69ac9bc59378dcc1be83c34589a2c37e371f27c6ff21505bd9a2d2f9f1accdd1b46e833

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
